import { Study } from './index';

export const DEFAULT_AIIA_STUDIES: Study[] = [
  {
    id: 'aiia-study-001',
    short_code: 'AIIA-ASHWA-001',
    title: 'Evaluation of Ashwagandha Ghan Vati in Mild-to-Moderate Generalized Anxiety Disorder',
    phase: 'Phase 2',
    study_type: 'Interventional RCT',
    status: 'ENROLLING',
    target_sample_size: 120,
    start_date: '2026-01-15',
    planned_end_date: '2027-06-30',
    study_arms: [
      {
        id: 'arm-1',
        arm_code: 'ARM-A',
        label: 'Arm A - Ashwagandha Ghan Vati 500mg BD',
        arm_type: 'EXPERIMENTAL',
        description: 'Standardized aqueous extract of Withania somnifera (5% Withanolides)',
        visit_definitions: [
          { id: 'v0', visit_name: 'Screening Visit', visit_day: 0, window_minus: 0, window_plus: 0, visit_type: 'SCREENING', is_mandatory: true },
          { id: 'v1', visit_name: 'Baseline Enrollment', visit_day: 1, window_minus: 0, window_plus: 0, visit_type: 'BASELINE', is_mandatory: true },
          { id: 'v2', visit_name: 'Follow-up 1 (Day 15)', visit_day: 15, window_minus: 3, window_plus: 3, visit_type: 'FOLLOW_UP', is_mandatory: true },
          { id: 'v3', visit_name: 'Follow-up 2 (Day 30)', visit_day: 30, window_minus: 3, window_plus: 3, visit_type: 'FOLLOW_UP', is_mandatory: true },
          { id: 'v4', visit_name: 'Closeout / Final Efficacy', visit_day: 60, window_minus: 5, window_plus: 5, visit_type: 'CLOSEOUT', is_mandatory: true },
        ],
      },
      {
        id: 'arm-2',
        arm_code: 'ARM-B',
        label: 'Arm B - Starch Placebo Comparator 500mg BD',
        arm_type: 'PLACEBO_COMPARATOR',
        description: 'Identical color, taste, and capsule appearance vehicle control',
        visit_definitions: [
          { id: 'v0-b', visit_name: 'Screening Visit', visit_day: 0, window_minus: 0, window_plus: 0, visit_type: 'SCREENING', is_mandatory: true },
          { id: 'v1-b', visit_name: 'Baseline Enrollment', visit_day: 1, window_minus: 0, window_plus: 0, visit_type: 'BASELINE', is_mandatory: true },
          { id: 'v2-b', visit_name: 'Follow-up 1 (Day 15)', visit_day: 15, window_minus: 3, window_plus: 3, visit_type: 'FOLLOW_UP', is_mandatory: true },
          { id: 'v3-b', visit_name: 'Follow-up 2 (Day 30)', visit_day: 30, window_minus: 3, window_plus: 3, visit_type: 'FOLLOW_UP', is_mandatory: true },
          { id: 'v4-b', visit_name: 'Closeout / Final Efficacy', visit_day: 60, window_minus: 5, window_plus: 5, visit_type: 'CLOSEOUT', is_mandatory: true },
        ],
      },
    ],
    ip_batches: [
      {
        id: 'batch-01',
        formulation_name: 'Ashwagandha Ghan Vati 500mg',
        batch_no: 'BATCH-ASHWA-2026-01',
        afi_api_standard_ref: 'Ayurvedic Pharmacopoeia of India (API) Part-1 Vol-1',
        current_stock: 4200,
      },
      {
        id: 'batch-02',
        formulation_name: 'Starch Placebo Vati 500mg',
        batch_no: 'BATCH-PLAC-2026-01',
        afi_api_standard_ref: 'In-house Formulation Spec (AIIA GMP Pharmacy)',
        current_stock: 4200,
      },
    ],
    iec_submissions: [
      {
        id: 'iec-sub-01',
        submission_date: '2025-12-05',
        decision: 'APPROVED',
        decision_date: '2026-01-10',
        valid_until: '2027-09-15',
        remarks: 'Ethics clearance approved unanimously under ICMR 2017 Guidelines and NDCT Rules 2019.',
      },
    ],
    ctri_registration: {
      ctri_id: 'CTRI/2026/01/041289',
      registration_date: '2026-01-20',
      next_mandatory_update_due: '2026-07-20',
    },
  },
  {
    id: 'aiia-study-002',
    short_code: 'AIIA-GUDUCHI-002',
    title: 'Standardized Guduchi (Tinospora cordifolia) Extract in Metabolic Syndrome & Immunomodulation',
    phase: 'Phase 2',
    study_type: 'Double Blind Parallel Group',
    status: 'IEC_APPROVED',
    target_sample_size: 100,
    start_date: '2026-02-01',
    planned_end_date: '2027-08-31',
    study_arms: [
      {
        id: 'arm-g1',
        arm_code: 'ARM-A',
        label: 'Arm A - Guduchi Hydroalcoholic Extract 500mg',
        arm_type: 'EXPERIMENTAL',
        description: 'Tinospora cordifolia stem extract with verified cordifolioside standard',
        visit_definitions: [
          { id: 'vg0', visit_name: 'Screening', visit_day: 0, window_minus: 0, window_plus: 0, visit_type: 'SCREENING', is_mandatory: true },
          { id: 'vg1', visit_name: 'Baseline', visit_day: 1, window_minus: 0, window_plus: 0, visit_type: 'BASELINE', is_mandatory: true },
          { id: 'vg2', visit_name: 'Mid-Point Evaluation', visit_day: 45, window_minus: 5, window_plus: 5, visit_type: 'FOLLOW_UP', is_mandatory: true },
          { id: 'vg3', visit_name: 'Study Closeout', visit_day: 90, window_minus: 7, window_plus: 7, visit_type: 'CLOSEOUT', is_mandatory: true },
        ],
      },
      {
        id: 'arm-g2',
        arm_code: 'ARM-B',
        label: 'Arm B - Active Control Comparator',
        arm_type: 'ACTIVE_COMPARATOR',
        description: 'Standard institutional standard of care adjuvant therapy',
        visit_definitions: [
          { id: 'vg0-b', visit_name: 'Screening', visit_day: 0, window_minus: 0, window_plus: 0, visit_type: 'SCREENING', is_mandatory: true },
          { id: 'vg1-b', visit_name: 'Baseline', visit_day: 1, window_minus: 0, window_plus: 0, visit_type: 'BASELINE', is_mandatory: true },
          { id: 'vg2-b', visit_name: 'Mid-Point Evaluation', visit_day: 45, window_minus: 5, window_plus: 5, visit_type: 'FOLLOW_UP', is_mandatory: true },
          { id: 'vg3-b', visit_name: 'Study Closeout', visit_day: 90, window_minus: 7, window_plus: 7, visit_type: 'CLOSEOUT', is_mandatory: true },
        ],
      },
    ],
    ip_batches: [
      {
        id: 'batch-gudu-01',
        formulation_name: 'Guduchi Extract 500mg Capsules',
        batch_no: 'BATCH-GUDU-2026-03',
        afi_api_standard_ref: 'Ayurvedic Pharmacopoeia of India (API) Part-1 Vol-2',
        current_stock: 2800,
      },
    ],
    iec_submissions: [
      {
        id: 'iec-sub-02',
        submission_date: '2026-01-05',
        decision: 'APPROVED',
        decision_date: '2026-02-14',
        valid_until: '2027-10-31',
        remarks: 'Institutional Ethics clearance granted. Awaiting CTRI public registration.',
      },
    ],
  },
  {
    id: 'aiia-study-003',
    short_code: 'AIIA-BRAHMI-003',
    title: 'Efficacy of Brahmi Ghrita in Age-Associated Memory Impairment (AAMI): Multicentric Trial',
    phase: 'Phase 3',
    study_type: 'Interventional RCT',
    status: 'IEC_SUBMITTED',
    target_sample_size: 250,
    start_date: '2026-03-01',
    planned_end_date: '2028-02-28',
    study_arms: [
      {
        id: 'arm-b1',
        arm_code: 'ARM-A',
        label: 'Arm A - Brahmi Ghrita 10ml Morning Dosing',
        arm_type: 'EXPERIMENTAL',
        description: 'Medicated Ghee prepared with Bacopa monnieri juice per Sharangadhara Samhita',
        visit_definitions: [
          { id: 'vb0', visit_name: 'Screening', visit_day: 0, window_minus: 0, window_plus: 0, visit_type: 'SCREENING', is_mandatory: true },
          { id: 'vb1', visit_name: 'Baseline Vitals & Prakriti', visit_day: 1, window_minus: 0, window_plus: 0, visit_type: 'BASELINE', is_mandatory: true },
          { id: 'vb2', visit_name: 'Follow-up 1', visit_day: 30, window_minus: 3, window_plus: 3, visit_type: 'FOLLOW_UP', is_mandatory: true },
          { id: 'vb3', visit_name: 'Closeout', visit_day: 90, window_minus: 5, window_plus: 5, visit_type: 'CLOSEOUT', is_mandatory: true },
        ],
      },
    ],
    ip_batches: [
      {
        id: 'batch-brah-01',
        formulation_name: 'Brahmi Ghrita Medicated Clarified Butter',
        batch_no: 'BATCH-BRAH-2026-01',
        afi_api_standard_ref: 'Ayurvedic Formulary of India (AFI) Part-1, 6:32',
        current_stock: 1500,
      },
    ],
    iec_submissions: [
      {
        id: 'iec-sub-03',
        submission_date: '2026-03-01',
        decision: 'PENDING_ETHICS_REVIEW',
        valid_until: '2027-12-31',
        remarks: 'Formal dossier submitted to AIIA Institutional Ethics Secretariat. Scheduled for committee review.',
      },
    ],
  },
];

export const DEFAULT_DOCUMENTS = [
  {
    id: 'doc-aiia-001',
    study_id: 'aiia-study-001',
    file_name: 'AIIA_ASHWA_Protocol_v2.4_Final.pdf',
    document_type: 'PROTOCOL_VERSION',
    sha256_hash: '8f4c2e5b7a1d3c9e6f0b4a2d8c1e7f3b5a9d2c6e4f8b1a7d3c5e9f2a4b6c8d1e',
    file_size: 2457600,
    uploaded_at: '2026-01-12T10:30:00Z',
    uploaded_by: 'dr.sharma@aiia.gov.in',
  },
  {
    id: 'doc-aiia-002',
    study_id: 'aiia-study-001',
    file_name: 'IEC_Clearance_AIIA_IEC_2026_01.pdf',
    document_type: 'IEC_APPROVAL_LETTER',
    sha256_hash: '3a7b9c1d5e2f4a6b8c0d2e4f6a8b0c2d4e6f8a0b2c4d6e8f0a2b4c6d8e0f2a4b',
    file_size: 1146880,
    uploaded_at: '2026-01-15T14:45:00Z',
    uploaded_by: 'ethics.sec@aiia.gov.in',
  },
  {
    id: 'doc-aiia-003',
    study_id: 'aiia-study-001',
    file_name: 'CoA_Ashwagandha_Batch_2026_01_GMP.pdf',
    document_type: 'DRUG_CERTIFICATE_OF_ANALYSIS',
    sha256_hash: 'b1c3d5e7f9a2c4e6a8b0d2f4a6c8e0b2d4f6a8c0e2b4d6f8a0c2e4b6d8f0a2c4',
    file_size: 892400,
    uploaded_at: '2026-01-18T09:15:00Z',
    uploaded_by: 'pharmacy.qa@aiia.gov.in',
  },
  {
    id: 'doc-aiia-004',
    study_id: 'aiia-study-001',
    file_name: 'Signed_Consent_SUBJ_AIIA_001_Hindi.pdf',
    document_type: 'SIGNED_INFORMED_CONSENT',
    sha256_hash: 'c4d6e8f0a2b4c6d8e0f2a4b6c8d0e2f4a6b8c0d2e4f6a8b0c2d4e6f8a0b2c4d6',
    file_size: 734000,
    uploaded_at: '2026-01-22T11:20:00Z',
    uploaded_by: 'crc.priya@aiia.gov.in',
  },
  {
    id: 'doc-aiia-005',
    study_id: 'aiia-study-001',
    file_name: 'AudioVisual_Vernacular_Consent_Video.mp4',
    document_type: 'VERNACULAR_CONSENT_MEDIA',
    sha256_hash: 'd5e7f9a1b3c5e7a9c1e3f5b7d9a1c3e5a7b9c1d3e5f7a9b1c3d5e7f9a1b3c5e7',
    file_size: 18874368,
    uploaded_at: '2026-01-22T11:25:00Z',
    uploaded_by: 'crc.priya@aiia.gov.in',
  },
];

export const DEFAULT_AUDIT_LOGS = [
  {
    id: 'audit-001',
    timestamp: '2026-03-05T09:15:22Z',
    user_email: 'dr.sharma@aiia.gov.in',
    user_role: 'PRINCIPAL_INVESTIGATOR',
    action: 'SUBJECT_ENROLLED',
    entity_type: 'ParticipantRecord',
    old_values: null,
    new_values: { subject_id: 'SUBJ-AIIA-001', arm: 'ARM-A', prakriti: 'VATA_PITTA' },
    reason: 'Subject satisfied all CDSCO/GCP inclusion and exclusion criteria at Baseline visit.',
  },
  {
    id: 'audit-002',
    timestamp: '2026-03-04T14:30:10Z',
    user_email: 'crc.priya@aiia.gov.in',
    user_role: 'COORDINATOR',
    action: 'CRF_VISIT_SUBMITTED',
    entity_type: 'ClinicalVisitCRF',
    old_values: { status: 'DRAFT', vitals_recorded: false },
    new_values: { status: 'COMMITTED', pulse_nadi: 'Mandooki', bp: '122/80' },
    reason: 'Completed Day 15 scheduled follow-up CRF with verified source documentation.',
  },
  {
    id: 'audit-003',
    timestamp: '2026-03-03T16:45:00Z',
    user_email: 'pharmacy.qa@aiia.gov.in',
    user_role: 'PHARMACY_CONTROLLER',
    action: 'IP_DISPENSED',
    entity_type: 'InvestigationalProductBatch',
    old_values: { current_stock: 4260 },
    new_values: { current_stock: 4200, dispensed_units: 60, batch_no: 'BATCH-ASHWA-2026-01' },
    reason: 'Dispensed 30-day bottle to Subject SUBJ-AIIA-002 per randomized arm protocol.',
  },
  {
    id: 'audit-004',
    timestamp: '2026-03-02T11:05:44Z',
    user_email: 'ethics.sec@aiia.gov.in',
    user_role: 'ETHICS_MEMBER_SECRETARY',
    action: 'IEC_APPROVAL_RECORDED',
    entity_type: 'EthicsSubmission',
    old_values: { status: 'PENDING_ETHICS_REVIEW' },
    new_values: { status: 'APPROVED', clearance_no: 'AIIA/IEC/2026/01/98' },
    reason: 'Formal clearance issued following unanimous committee decision at 42nd IEC meeting.',
  },
  {
    id: 'audit-005',
    timestamp: '2026-03-01T08:20:15Z',
    user_email: 'dr.sharma@aiia.gov.in',
    user_role: 'PRINCIPAL_INVESTIGATOR',
    action: 'PROTOCOL_LOCKED',
    entity_type: 'StudyProtocol',
    old_values: { status: 'DRAFT', version: '2.3' },
    new_values: { status: 'SUBMITTED', version: '2.4' },
    reason: 'Protocol locked for institutional regulatory submission under CDSCO New Drugs and Clinical Trials Rules 2019.',
  },
];

export const DEFAULT_CDISC_PACKAGE = {
  cdisc_version: 'SDTM v1.7 / SEND v3.1',
  study_metadata: {
    study_id: 'AIIA-ASHWA-001',
    title: 'Evaluation of Ashwagandha Ghan Vati in Generalized Anxiety Disorder',
    phase: 'Phase 2',
    study_type: 'Interventional RCT',
    ctri_id: 'CTRI/2026/01/041289',
    generated_at: new Date().toISOString(),
  },
  domains: {
    DM: [
      {
        USUBJID: 'SUBJ-AIIA-001',
        AGE: 34,
        SEX: 'F',
        ARM: 'ARM-A',
        PRAKRITI: 'Vata-Pitta',
        PATHYA_DIET_SCORE: 88,
        RFSTDTC: '2026-01-22',
      },
      {
        USUBJID: 'SUBJ-AIIA-002',
        AGE: 42,
        SEX: 'M',
        ARM: 'ARM-B',
        PRAKRITI: 'Pitta-Kapha',
        PATHYA_DIET_SCORE: 92,
        RFSTDTC: '2026-01-24',
      },
      {
        USUBJID: 'SUBJ-AIIA-003',
        AGE: 29,
        SEX: 'F',
        ARM: 'ARM-A',
        PRAKRITI: 'Vata-Kapha',
        PATHYA_DIET_SCORE: 76,
        RFSTDTC: '2026-01-28',
      },
      {
        USUBJID: 'SUBJ-AIIA-004',
        AGE: 51,
        SEX: 'M',
        ARM: 'ARM-A',
        PRAKRITI: 'Tridoshaja',
        PATHYA_DIET_SCORE: 85,
        RFSTDTC: '2026-02-02',
      },
    ],
    EX: [
      {
        EXTRT: 'Ashwagandha Ghan Vati 500mg',
        EXLOT: 'BATCH-ASHWA-2026-01',
        EXSTD: 'API Part-1 Vol-1',
        EXDOSE: 120,
        EXDOSU: 'Tablets',
      },
      {
        EXTRT: 'Starch Placebo Vati 500mg',
        EXLOT: 'BATCH-PLAC-2026-01',
        EXSTD: 'In-house GMP',
        EXDOSE: 120,
        EXDOSU: 'Tablets',
      },
    ],
    AE: [
      {
        USUBJID: 'SUBJ-AIIA-003',
        AETERM: 'Mild Koshtha Rookshata (Dryness in digestion)',
        AESEV: 'MILD',
        AEREL: 'POSSIBLE',
        AESER: 'N',
        AEOUT: 'RESOLVED',
        AESTDTC: '2026-02-10',
      },
    ],
  },
};

